# Start from a lightweight Python image
FROM python:3.11-slim

# Set working directory inside the container
WORKDIR /code

# Copy requirements and install them
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy your app code into the container
COPY ./app /code/app

# Command to run the app when the container starts
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
